### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by antgustech** [windward-studios/Windward-RESTful-V2-.NET-Framework-Client-Sample#1]
How do I get started with using this? Where can I find the documentation? The only resources I have found are here: https://ohana.windwardstudios.com/ but they do not describe on how to use the the API.

**Comment by zaidabuhijlehWindward** [comment]
Hello, 
Thank you for reaching out. We are currently working on adding documentation to help with the usage of the clients. You can use the sample application as a guide to see what methods are called and so on. I would recommend taking a look at the JavaScript client sample app https://github.com/windward-studios/Windward-RESTful-V2-JavaScript-Client-Sample (test.js) as it is a simpler example to see how to use the client (all method names and all of that are the same). The .NET samples are more robust and show you the full extent of the client. If you have any more questions please reach out to our sales team at (sales@windward.net) or you can reach me directly at zaida@windwardstudios.com.

**Comment by zaidabuhijlehWindward** [comment]
Swagger Documentation: https://app.swaggerhub.com/apis/Windward-Studios/windward-rest_ful_api/2.0#/

Internal documentation: https://ohana.windwardstudios.com/m/79043/l/1428656-restful-engine-v2-net-client-reference
